# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./f1-driver-landing
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:      
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Clean npm cache
      run: npm cache clean --force   
      
    - name: Remove node_modules and package-lock.json
      run: |
        rm -rf node_modules
        rm -f package-lock.json
    
    - name: Install dependencies with legacy peer deps    
      run: npm install --legacy-peer-deps    
    - run: npm run build
